default_context:
  project_name: 'bfx-ftx-rest-api'
  project_slug: 'bfx-ftx-rest-api'
  domain_main: 'bfx-ftx-rest-api.com'
  domain_staging: 'stag.bfx-ftx-rest-api.com'
  docker_swarm_stack_name_main: 'bfx-ftx-rest-api-com'
  docker_swarm_stack_name_staging: 'stag-bfx-ftx-rest-api-com'
  secret_key: '67c02e8bdbdbb9f81f0c7c15622f3ac85b9f5f094f0565bf2a221e77cb267ecb'
  first_superuser: 'admin'
  first_superuser_password: '123'
  backend_cors_origins: '["http://localhost", "http://localhost:4200", "http://localhost:3000", "http://localhost:8080", "https://localhost", "https://localhost:4200", "https://localhost:3000", "https://localhost:8080", "http://dev.bfx-ftx-rest-api.com", "https://stag.bfx-ftx-rest-api.com", "https://bfx-ftx-rest-api.com", "http://local.dockertoolbox.tiangolo.com", "http://localhost.tiangolo.com"]'
  smtp_port: '587'
  smtp_host: ''
  smtp_user: 'admin'
  smtp_password: '123'
  smtp_emails_from_email: 'info@bfx-ftx-rest-api.com'
  postgres_password: 'postgres'
  pgadmin_default_user: 'admin'
  pgadmin_default_user_password: '123'
  traefik_constraint_tag: 'bfx-ftx-rest-api.com'
  traefik_constraint_tag_staging: 'stag.bfx-ftx-rest-api.com'
  traefik_public_constraint_tag: 'traefik-public'
  flower_auth: 'admin:123'
  sentry_dsn: ''
  docker_image_prefix: ''
  docker_image_backend: 'backend'
  docker_image_celeryworker: 'celeryworker'
  docker_image_frontend: 'frontend'
  _copy_without_render: [frontend/src/**/*.html, frontend/src/**/*.vue, frontend/node_modules/*, backend/app/app/email-templates/**]
  _template: ./
